services:
  web:
    build: .
    ports:
      - "5002:5000"       # 浏览器访问 http://localhost:5002
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      MONGO_DBNAME: budget_app
      
      MONGO_URI: "mongodb+srv://yuxuanf2005_db_user:VaqrvDySP1LPLlHg@cluster0.rcxky03.mongodb.net/budget_app?retryWrites=true&w=majority&appName=Cluster0"
    
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27019:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
